### ISSUE TITLE
Stabilize `MISSING` sentinel feature

### ISSUE THREAD

**Issue by Viicos** [pydantic/pydantic#12090]
This will depend on the fate of [PEP 661](https://peps.python.org/pep-0661/).

Things to consider:
- [x] We probably should push down constraints, e.g. `int | MISSING = Field(gt=1)` should be equivalent to `Annotated[int, Gt(1)] | MISSING`. What about `int | None | MISSING`? https://github.com/pydantic/pydantic/pull/12908
- [x] When validation fails for  `<typ> | MISSING`, we shouldn't mention `MISSING` as an allowed value in the validation error. This may require some changes in the core schema logic (currently this is a union, which shouldn't have special knowledge about `MISSING` being one of the union members, so we probably need something similar to the `'nullable'` schema). https://github.com/pydantic/pydantic/pull/13779
- Related to previous point, should `MISSING` actually be allowed as a value? Is there a use case where explicitly allowing `MISSING` (only possible from Python, not JSON) makes sense? Shouldn't it be some kind of implementation detail? Final decision: we decided it should be allowed, as it would otherwise contradict static type checkers, and we can see how it can be useful (e.g. setting a field to `MISSING` after validation to exclude it).

    ```python
    class Model(BaseModel):
        a: int | MISSING = MISSING

    model = Model(a=MISSING)  # This currently works

    # As per the type checking rules for sentinels, this is a static type checker error:
    class Model(BaseModel):
        a: int = MISSING

    # .. if this was possible, then the sentinel is only relevant as a default value. Conceptually, it means
    # *not* having a default value is a logical error?
    class Model(BaseModel):
        a1: int
        # equivalent to?:
        a2: int | MISSING
    ```

**Comment by pycaw** [comment]
Doesn't it make sense to make it _falsy_? As in, derive from `Sentinel`, add,
```py
def __bool__(self) -> Literal[False]:
    return False
```
and use that as our `MISSING`'s class?
As of yet though, pyright considers this kind of Sentinel as `UNKNOWN` instead of `MISSING`.

**Comment by Viicos** [comment]
> Doesn't it make sense to make it _falsy_?

That's not for me to say, but up to the PEP author. There is some discussion about truthiness in the linked discussion thread (my personal opinion is that truthiness shouldn't be supported and `__bool__()` should raise an error to avoid unexpected behavior).

> As of yet though, pyright considers this kind of Sentinel as `UNKNOWN` instead of `MISSING`.

As mentioned in the [documentation](https://docs.pydantic.dev/dev/concepts/experimental/#missing-sentinel), `enableExperimentalFeatures` needs to be set.

**Comment by pycaw** [comment]
> `enableExperimentalFeatures` needs to be set.

I meant if you subclass Sentinel then it will break.

It seems to me it's a pretty good use case for falsiness but I will indulge in those discussions.

**Comment by pycaw** [comment]
I noticed the behavior below.

I assume this is not intended. Why don't we have `pattern` as part of `ClassWithMissing`'s schema as with `ClassWithNone`?

Removing the default values will produce the same outcome regarding `pattern`'s existence. And using `str | None | MISSING` as type hint will also result in nullified constraints.

```py
import json
import warnings
from typing import Annotated

from pydantic import BaseModel, Field, PydanticExperimentalWarning

warnings.filterwarnings("ignore", category=PydanticExperimentalWarning)

from pydantic.experimental.missing_sentinel import MISSING  # noqa: E402


class ClassWithMissing(BaseModel):
    value: Annotated[str | MISSING, Field(pattern=r"\d?")] = MISSING


class ClassWithNone(BaseModel):
    value: Annotated[str | None, Field(pattern=r"\d?")] = None


def test():
        assert (
        json.dumps(ClassWithMissing.model_json_schema(), indent=4)
        == """{
    "properties": {
        "value": {
            "title": "Value",
            "type": "string"
        }
    },
    "title": "ClassWithMissing",
    "type": "object"
}"""
    )
    assert (
        json.dumps(ClassWithNone.model_json_schema(), indent=4)
        == r"""{
    "properties": {
        "value": {
            "anyOf": [
                {
                    "pattern": "\\d?",
                    "type": "string"
                },
                {
                    "type": "null"
                }
            ],
            "default": null,
            "title": "Value"
        }
    },
    "title": "ClassWithNone",
    "type": "object"
}"""
    )

test()
```

**Comment by bjmc** [comment]
I'm guessing this is a foreseeable limitation, but being unable to Pickle `MISSING` unfortunately also means you can't use `model_copy(deep=True)` on any models with MISSING fields:

```python
from pydantic.experimental.missing_sentinel import MISSING
from pydantic import BaseModel

class ExampleModel(BaseModel):
    name: str | MISSING = MISSING


unnamed = ExampleModel()
# Shallow copy is okay
shallow_copy = unnamed.model_copy(deep=False)  # ExampleModel(name=<MISSING>)
# But deep copy relies on pickle:
deep_copy = unnamed.model_copy(deep=True)
# Traceback (most recent call last):
#   File "/home/bjmc/Sandbox/example.py", line 12, in <module>
#     deep_copy = unnamed.model_copy(deep=True)
#   File "/home/bjmc/.cache/pypoetry/virtualenvs/zPbyUnCb-py3.10/lib/python3.10/site-packages/pydantic/main.py", line 406, in model_copy
#     copied = self.__deepcopy__() if deep else self.__copy__()
#   File "/home/bjmc/.cache/pypoetry/virtualenvs/zPbyUnCb-py3.10/lib/python3.10/site-packages/pydantic/main.py", line 941, in __deepcopy__
#     _object_setattr(m, '__dict__', deepcopy(self.__dict__, memo=memo))
#   File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
#     y = copier(x, memo)
#   File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
#     y[deepcopy(key, memo)] = deepcopy(value, memo)
#   File "/usr/lib/python3.10/copy.py", line 161, in deepcopy
#     rv = reductor(4)
#   File "/home/bjmc/.cache/pypoetry/virtualenvs/zPbyUnCb-py3.10/lib/python3.10/site-packages/typing_extensions.py", line 4245, in __getstate__
#     raise TypeError(f"Cannot pickle {type(self).__name__!r} object")
# TypeError: Cannot pickle 'Sentinel' object
```

Is there any chance this could be fixed or worked around with special logic inside `model_copy()`?

**Comment by Viicos** [comment]
> I assume this is not intended. Why don't we have `pattern` as part of `ClassWithMissing`'s schema as with `ClassWithNone`?
> 
> Removing the default values will produce the same outcome regarding `pattern`'s existence. And using `str | None | MISSING` as type hint will also result in nullified constraints.

Pydantic has some special casing on `<typ> | None` types, where constraints applied using `Annotated` to the _whole_ union (and not just `<typ>`) are applied to `<typ>` directly. I don't like this special casing as it is inconsistent with the rest of the logic, and we then face the issue for the `MISSING` sentinel that could behave the same. I'll discuss with the team shortly.

---

> I'm guessing this is a foreseeable limitation, but being unable to Pickle `MISSING` unfortunately also means you can't use `model_copy(deep=True)` on any models with MISSING fields:

@bjmc This will depend on the semantics of [PEP 661](https://peps.python.org/pep-0661/) once it is submitted. There is some ongoing discussion about sentinels being pickleable in the [discussion thread](https://discuss.python.org/t/9126/).

**Comment by bjmc** [comment]
Even if it turns out that sentinels are non-pickleable, would it be possible for `model_copy(deep=True)` to treat `MISSING` as a special case singleton? (i.e. don't try to copy it) The fact that deepcopy relies on pickle machinery seems like an implementation detail callers shouldn't have to be concerned with.

**Comment by Viicos** [comment]
If sentinels end up being non-pickleable (I hope they will), we will find an alternative (may require _not_ using PEP 661 sentinels) that will support it.

**Comment by pycaw** [comment]
For the sake of syntactic brevity, not requiring in each cases where MISSING is used in conjunction with some constrained type to have that be wrapped in a RootModel would be appreciated. Road is already paved with None's treatment. The two would have better synergy as well it looks.

**Comment by Viicos** [comment]
> For the sake of syntactic brevity, not requiring in each cases where MISSING is used in conjunction with some constrained type to have that be wrapped in a RootModel would be appreciated.

I fail to understand what you mean. Do you have an example?

**Comment by pycaw** [comment]
> > For the sake of syntactic brevity, not requiring in each cases where MISSING is used in conjunction with some constrained type to have that be wrapped in a RootModel would be appreciated.
> 
> I fail to understand what you mean. Do you have an example?

I meant this:

```py
class A(BaseModel):
    value: Annotated[str | MISSING, constr(min_length=1)] = MISSING


class Value(RootModel):
    root: Annotated[str, constr(min_length=1)]


class B(BaseModel):
    value: Value | MISSING = MISSING


print(json.dumps(A.model_json_schema(), indent=4))
print(json.dumps(B.model_json_schema(), indent=4))
```

But I don't know where I got the idea. Version `B` doesn't preserve the constraint either actually.

**Comment by pycaw** [comment]
~~Is the example above not a gigantic bug with this feature? Should I open an issue about it?~~ -- `constr` was used erroneously here -- And what is the currently advised way of applying constraints together with `MISSING`?

**Comment by Viicos** [comment]
You are not using `constr()` the expected way. The `con*` functions are meant to be used directly as type annotations, this way:

```python
class Model(BaseModel):
    a: constr(min_length=1)
```

Usage of these functions are discouraged anyway (and we'll actually properly deprecate them in 2.12 -- it's a shame that we didn't properly remove them from the documentation). Instead, the `Field()` function or the `StringConstraints` metadata class can be used:

```python
class Model(BaseModel):
    a: Annotated[str, StringConstraints(min_length=1)]
```

---

Regarding applying constraints to a union (instead of the specific member of the union), Pydantic has some special casing _if_ the union is a `<typ> | None` form. I'm not a fan of this behavior (see https://github.com/pydantic/pydantic/issues/11500#issuecomment-2733779987 for an example), but we unfortunately can't deprecate this behavior as we noticed widespread usage from Github searches. We are going to document it, and most likely also apply this special casing for the `MISSING` sentinel.

**Comment by pycaw** [comment]
<details>
<summary><i>You are not using <code>constr()</code>...</i></summary>

> You are not using `constr()` the expected way. The `con*` functions are meant to be used directly as type annotations, this way:
> 
> class Model(BaseModel):
>     a: constr(min_length=1)
> 
> Usage of these functions are discouraged anyway (and we'll actually properly deprecate them in 2.12 -- it's a shame that we didn't properly remove them from the documentation). Instead, the `Field()` function or the `StringConstraints` metadata class can be used:
> 
> class Model(BaseModel):
>     a: Annotated[str, StringConstraints(min_length=1)]
> 
> Regarding applying constraints to a union (instead of the specific member of the union), Pydantic has some special casing _if_ the union is a `<typ> | None` form. I'm not a fan of this behavior (see [#11500 (comment)](https://github.com/pydantic/pydantic/issues/11500#issuecomment-2733779987) for an example), but we unfortunately can't deprecate this behavior as we noticed widespread usage from Github searches. We are going to document it, and most likely also apply this special casing for the `MISSING` sentinel.

</details>

Oh, okay (I don't use `constr`, sorry about that).
~~But, if you substitute `constr` with `Field` (or `StringConstraints`) you get the same erroneous behavior with classes `Value` + `B` (and of course with `A`). Constraint is gone.~~

**Comment by Viicos** [comment]
> But, if you substitute `constr` with `Field` (or `StringConstraints`) you get the same erroneous behavior with classes `Value` + `B` (and of course with `A`). Constraint is gone.

I do see the constraint with the following:

```python
class Value(RootModel):
    root: Annotated[str, StringConstraints(min_length=1)]

class B(BaseModel):
    value: Value | MISSING = MISSING

B.model_json_schema()

{
│   '$defs': {'Value': {'minLength': 1, 'title': 'Value', 'type': 'string'}},
│   'properties': {'value': {'$ref': '#/$defs/Value'}},
│   'title': 'B',
│   'type': 'object'
}
```

**Comment by pycaw** [comment]
<details>
<summary><i>I do see the constraint...</i></summary>

> > But, if you substitute `constr` with `Field` (or `StringConstraints`) you get the same erroneous behavior with classes `Value` + `B` (and of course with `A`). Constraint is gone.
> 
> I do see the constraint with the following:
> 
> class Value(RootModel):
>     root: Annotated[str, StringConstraints(min_length=1)]
> 
> class B(BaseModel):
>     value: Value | MISSING = MISSING
> 
> B.model_json_schema()
> 
> {
> │   '$defs': {'Value': {'minLength': 1, 'title': 'Value', 'type': 'string'}},
> │   'properties': {'value': {'$ref': '#/$defs/Value'}},
> │   'title': 'B',
> │   'type': 'object'
> }

</details>

Indeed, I screwed up my tests...

On another note, some constraints now are preserved (without involving `RootModel`), like in the following case:
```py
class ClassWithMissing_int(BaseModel):
    value: Annotated[int | MISSING, Field(ge=1)] = MISSING
```

**Comment by Viicos** [comment]
> On another note, some constraints now are preserved (without involving `RootModel`), like in the following case:

Yeah this is because Pydantic still tries to apply a validator as a Python function (that will check for `>= value`), but this is different from having the `ge` constraint applied to the `int` type directly (in which case the validation happens in pydantic-core more efficiently.

**Comment by marianhlavac** [comment]
Using the experimental `MISSING`, Pylance reports this as:

_Variable not allowed in type expression Pylance ([reportInvalidTypeForm](https://github.com/microsoft/pylance-release/blob/main/docs/diagnostics/reportInvalidTypeForm.md))_

<img width="1050" height="847" alt="Screenshot 2025-10-02 at 14 32 57" src="https://github.com/user-attachments/assets/c0b4a66e-7078-46a1-aa84-8e195e6469ba" />

**Comment by bjmc** [comment]
@marianhlavac this [is covered in the docs.](https://docs.pydantic.dev/dev/concepts/experimental/#missing-sentinel)

>Static type checking of sentinels is only supported with Pyright [1.1.402](https://github.com/microsoft/pyright/releases/tag/1.1.402) or greater, and the enableExperimentalFeatures type evaluation setting should be enabled.

You have to set `enableExperimentalFeatures` to `true` in your config or you get errors from the type-checker.

**Comment by vipierozan99** [comment]
I tested it with `pydantic==2.14.2` and `pyright==1.1.407` (with `enableExperimentalFeatures = true`), while the model definition works, when I try to access the field I get `str | Unknown`, probably an update needed on pyright but it's not usable on this state :( 

```py
class Foo(BaseModel):
    name: str | MISSING = MISSING # This is fine


foo = Foo.model_validate({})
reveal_type(foo.name)  # Type is str | Unknown

if not isinstance(foo.name, MISSING):  # Doesnt work
    foo.name

if foo.name is MISSING:
    reveal_type(foo.name) # Still str | Unknown
else:
    reveal_type(foo.name)  # Still str | Unknown

if foo.name is not MISSING:
    reveal_type(foo.name)  # Still str | Unknown
```

**Comment by pycaw** [comment]
> I tested it with `pydantic==2.14.2` and `pyright==1.1.407` (with `enableExperimentalFeatures = true`), while the model definition works, when I try to access the field I get `str | Unknown`, probably an update needed on pyright but it's not usable on this state :(
> 
> class Foo(BaseModel):
>     name: str | MISSING = MISSING # This is fine
> 
> 
> foo = Foo.model_validate({})
> reveal_type(foo.name)  # Type is str | Unknown
> 
> if not isinstance(foo.name, MISSING):  # Doesnt work
>     foo.name
> 
> if foo.name is MISSING:
>     reveal_type(foo.name) # Still str | Unknown
> else:
>     reveal_type(foo.name)  # Still str | Unknown
> 
> if foo.name is not MISSING:
>     reveal_type(foo.name)  # Still str | Unknown

Is `enableExperimentalFeatures` set?
```
[tool.pyright]
enableExperimentalFeatures = true
```

**Comment by vipierozan99** [comment]
> Is `enableExperimentalFeatures` set?
> 
> ```
> [tool.pyright]
> enableExperimentalFeatures = true
> ```
Yes, otherwise I get an error on here:

```py
class Foo(BaseModel):
    name: str | MISSING = MISSING # <- HERE
```

As @marianhlavac showed

**Comment by Viicos** [comment]
@vipierozan99 this is a pyright regression: https://github.com/microsoft/pyright/issues/11115.

**Comment by Ksauder** [comment]
Is this intended behavior @Viicos ?
```python
from typing import TypeVar, Union, Annotated

from pydantic import Field, BaseModel, create_model, BeforeValidator
from pydantic_core import PydanticUseDefault
from pydantic.experimental.missing_sentinel import MISSING
import pytest

## workaround forcing use of the default, which I believe just short circuits other validation
def use_default(value):
    if value is MISSING:
        raise PydanticUseDefault()
    return value

T = TypeVar("T")
type Omissible[T] = Annotated[Union[T, MISSING], BeforeValidator(use_default)]
##

def test_missing_sentinel():
    dynmod = create_model("DynamicModel", name=(str | MISSING, Field(MISSING, max_length=20)))
    dynmod()  # works
    dynmod(name="Sam")  # works
    with pytest.raises(TypeError, match="Unable to apply constraint 'max_length' to supplied value <MISSING>"):
        dynmod(name=MISSING)  # errors: TypeError: Unable to apply constraint 'max_length' to supplied value <MISSING>

    dynmod_no_constraint = create_model("DynamicModelNC", name=(str | MISSING, Field(MISSING)))
    dynmod_no_constraint()  # works: DynamicModelNC(name=<MISSING>)
    dynmod_no_constraint(name="Sam")  # works: DynamicModelNC(name=Sam)
    dynmod_no_constraint(name=MISSING)  # works: DynamicModelNC(name=<MISSING>)

    # workaround
    dynmod_use_default = create_model("DynamicModelDefault", name=(Omissible[str], Field(MISSING, max_length=20)))
    dynmod_use_default()  # works: DynamicModelDefault(name=<MISSING>)
    dynmod_use_default(name="Sam")  # works: DynamicModelDefault(name=Sam)
    dynmod_use_default(name=MISSING)  # works: DynamicModelDefault(name=<MISSING>)

```
Running in to this when composing some models together and then running .model_validate() on them. I can probably change that to make sure MISSING values are dropped, but conceptually this seems like it should work to me. Or at least be consistent so setting MISSING explicitly just fails, but then that's conceptually confusing since it's also an acceptable default value.

**Comment by Viicos** [comment]
@Ksauder see https://github.com/pydantic/pydantic/issues/12090#issuecomment-3316061651.

**Comment by Ksauder** [comment]
Essentially meaning that None could be in a Union that has constraints placed on it and not be validated by those same constraints?

I fixed my issue by ensuring validation is only applied to the relevant types and not to a union that includes MISSING.
Is it still planned to special case MISSING?

**Comment by Viicos** [comment]
> Is it still planned to special case MISSING?

Yes, it is still planned.

**Comment by WilliamDEdwards** [comment]
While I am aware that the implementation details depend on the PEP, I'd like to just drop a note here stating that this feature is much, much, much-wanted. Being able to differentiate between 'value missing' and 'value is null' is a must for mature APIs (which Pydantic is often used in conjunction with).

**Comment by JiwaniZakir** [comment]
The key challenge here is the union schema handling — right now `MISSING` is just another union member, so validation errors list it as an allowed type, which is confusing for users. I'd approach this by introducing a dedicated schema type similar to `'nullable'` in pydantic-core that wraps the inner type and handles the `MISSING` sentinel transparently, so the validator never exposes it in error messages. That also gives us a clean place to push down constraints like `Gt(1)` to the inner type rather than applying them to the union, and to decide whether `Model(a=MISSING)` should actually validate or be rejected at the core level.

**Comment by JiwaniZakir** [comment]
Stepping back from this one — the fix turned out to be more complex than expected and I ran out of time. Leaving this open for someone else.

**Comment by SyntaxColoring** [comment]
Can this Pydantic feature get reworked so that it does not depend on PEP 661? [PEP 661 is deferred](https://peps.python.org/pep-0661/). It's not safe to assume we're ever going to get it. To me, this is a big enough feature gap that Pydantic ought to have *something* (non-experimental!), even if we can't have our ideal PEP-standardized world.

Without PEP 661, the syntax for this feature could be like:

```python
class MyBaseModel(BaseModel):
    # Parsing from JSON, this can be true, false, null, or omitted entirely.
    my_field: bool | None | MissingType = MISSING
```

Here, Pydantic defines `MISSING` and `MissingType` through one of the "old-fashioned" ways, e.g. a single-valued `enum`, or `object()`, or whatever.

This is the approach taken by msgspec ([source](https://github.com/jcrist/msgspec/blob/a9ed8f12f11269704aa25680a2273287485c9f5a/src/msgspec/__init__.pyi#L71-L74), [docs](https://jcristharif.com/msgspec/api.html#unset)), and as far as I know, it works well enough for them.

**Comment by andrew222651** [comment]
The approach I've been using is to define this class
```python
class Unset:
    def __bool__(self) -> Literal[False]:
        return False

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: Any, handler: GetCoreSchemaHandler
    ) -> CoreSchema:
        def validate(value):
            if not isinstance(value, source_type):
                raise ValueError(
                    f"Expected an instance of {source_type}, got an instance of {type(value)}"
                )
            return value

        return core_schema.no_info_plain_validator_function(validate)
```

Then in a model, do this:
```python
class Foo(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)

    fieldname: str | Unset = Field(default_factory=Unset)
```

I haven't had any warnings and the JSON schema is as expected.

**Comment by Viicos** [comment]
> Can this Pydantic feature get reworked so that it does not depend on PEP 661? [PEP 661 is deferred](https://peps.python.org/pep-0661/). It's not safe to assume we're ever going to get it.

It was close to completion during the past year, but stalled again. I [reached out](https://discuss.python.org/t/9126/319), hopefully we will be able to get some progress. 2.13.0 was just released, which gives us some months before the next Pydantic release. If we don't get any progress, then we will consider an alternative solution.

**Comment by ari-bou** [comment]
> Can this Pydantic feature get reworked so that it does not depend on PEP 661? [PEP 661 is deferred](https://peps.python.org/pep-0661/).

Small update: PEP 661 has since been accepted and the implementation is slated for python 3.15.

**Comment by fregataa** [comment]
Hi, I am curious about this issue. Has this already addressed by #12908 or is there any remaining issue?

**Comment by lumpi101** [comment]
I really like that feature but there is still one little thing I'd like to see changed:
```python
# works
class Foo(BaseModel):
    a: int | MISSING = MISSING
 
# IMHO should work, too but fails on initialization without `a`
class Bar(BaseModel):
    a: int | MISSING
```

I think `a: int | MISSING` should suffice to declare values to be non-required, without `= MISSING`.
`MISSING` already states "this field may be missing". Requiring `= MISSING` on top means stating the same fact twice, through two different mechanisms (annotation and default).
Semantically, the default on top is actually a no-op. A default replaces absence with a value; this one replaces absence with absence. It's technically not wrong (and should not lead to an error) but it should not be necessary.
I'd guess `int | MISSING` without a default would be more intuitive for people (at least it is for me). People who forget the `= MISSING` part will get an error at initialization and the error message `Field required [type=missing, input_value={}, input_type=dict]` is not really helpful IMHO.

**Comment by Viicos** [comment]
> I think `a: int | MISSING` should suffice to declare values to be non-required, without `= MISSING`.

Not sure I agree: this goes strongly against type checking behavior for dataclass-like constructs such as Pydantic models. If no default value is present, the field is required. We moved away from this pattern with `None` in V1 already (https://pydantic.dev/docs/validation/latest/get-started/migration/#required-optional-and-nullable-fields), I don't think it's a good idea to reintroduce it. Besides, adding the default value costs nothing to the user.

> People who forget the `= MISSING` part will get an error at initialization and the error message `Field required [type=missing, input_value={}, input_type=dict]` is not really helpful IMHO.

We are most likely going to change the behavior before stabilization, as per my OP in this issue.

**Comment by lumpi101** [comment]
I see your point and for the `None` case I totally agree. `None` or `null` in json is an explicit value just like any other value in that sense and should not be assumed to be present in the data when it's not. But I think `MISSING` is still another case because it denotes non-requiredness. It's its sole purpose (a non-required value is allowed to be missing).

> If no default value is present, the field is required.

Yes, defaults used to be the means to denote that a field is non-required but with the downside that it is always replaced with a default value. It coupled the two concepts of "non-required values" and "default values".
Now `MISSING` steps in to decouple these concepts, and one don't need a default anymore to represent a non-required field. An absent field in the data directly translates into the explicit `MISSING` singleton inside pydantic - no default value is needed here.

I'm not sure I could make my point. But I guess there are different views possible on that topic.

**Comment by Viicos** [comment]
I kind of get the point, related to my last bullet in OP:

> Related to previous point, should `MISSING` actually be allowed as a value? Is there a use case where explicitly allowing `MISSING` (only possible from Python, not JSON) makes sense? Shouldn't it be some kind of implementation detail?

If we went this way, with `f: int | MISSING`, only allowing `int` would mean it is equivalent (at least on the validation side) to just `int`. But I still don't think it's a good idea: what prevents users from defining the `= MISSING` default, apart from saving a few keystrokes? How often are we going to have reports about users _not_ specifying the default and complaining about "my static type checker raises an error even though Pydantic fills the default, why are you allowing this in the first place?"?

I also think there could be a use case with `int | MISSING` without a default: the field is required (and -- depending on whether we allow explicit `MISSING` -- only an `int` can be provided), but can later be set to `MISSING` so that it's excluded from serialization. With your current proposal, this would no longer be possible.

**Comment by lumpi101** [comment]
It's not quite what I mean. I think our misunderstanding comes from very different points of view. I guess you are very close to the implementation/code while I only looked at how a model definition with `MISSING` should look like for me to make most sense. Not so much about saving keystrokes.

What I did not see before was the point with the type checkers. If I got you right, they generally assume values to be required when they have no default defined, right? So static type checking would fail with my suggestion. And that would be bad. That's the point where you convinced me :)
So yes you are right, it would be a bad idea.

**Comment by Viicos** [comment]
Yes so in:

```python
class Model(BaseModel):
    a: int | MISSING

Model()  # type checker error: a is required
```

and my point was that unless I'm missing something, users can just add the default to solve it:

```python
class Model(BaseModel):
    a: int | MISSING = MISSING  # equivalent according to your proposal
```

**Comment by Viicos** [comment]
https://github.com/pydantic/pydantic/pull/13779 updates the validation logic so that `MISSING` isn't reported as a possible value anymore (the runtime still allows explicitly passing `MISSING`, although it isn't the intended primary case).

With that merged, we are ready to [stabilize](https://github.com/pydantic/pydantic/pull/13782) this feature for the next release.

**Comment by lenard-mosys** [comment]
> I also think there could be a use case with int | MISSING without a default: the field is required (and -- depending on whether we allow explicit MISSING -- only an int can be provided), but can later be set to MISSING so that it's excluded from serialization. With your current proposal, this would no longer be possible.

I'm not sure I like that. Does that mean that such a model can be used to serialize to a json document that does not validate with the same model or the corresponding json schema?

It would be nice if roundtripping a model instance through model_dump_json() -> model_validate_json() were safe by default, but maybe it is already broken in other ways.

**Comment by Viicos** [comment]
> I'm not sure I like that. Does that mean that such a model can be used to serialize to a json document that does not validate with the same model or the corresponding json schema?
> 
> It would be nice if roundtripping a model instance through model_dump_json() -> model_validate_json() were safe by default, but maybe it is already broken in other ways.

In this particular case, it wouldn't roundtrip, but _not_ setting a default `= MISSING` for such fields is pretty contrived to begin with.
