### ISSUE TITLE
pydantic.v1.parse_obj_as internally uses pydantic.main.create_model instead of pydantic.v1.main.create_model

### ISSUE THREAD

**Issue by SharathHuddar** [pydantic/pydantic#6361]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

I was trying to migrate my codebase from V1 to V2 (mostly by replacing `import pydantic` with `import pydantic.v1`) and noticed that `pydantic.v1.parse_obj_as` was not working as intended and was leading to the following error:

```
Traceback (most recent call last):
  File "/Users/sharathhuddar/workspace/django-rest-api/core/tests/test_types.py", line 177, in test_non_https_url
    parse_obj_as(HttpsUrl, url)
  File "/Users/sharathhuddar/workspace/django-rest-api/django-rest-api-3.7/lib/python3.7/site-packages/pydantic/v1/tools.py", line 37, in parse_obj_as
    model_type = _get_parsing_type(type_, type_name=type_name)  # type: ignore[arg-type]
  File "/Users/sharathhuddar/workspace/django-rest-api/django-rest-api-3.7/lib/python3.7/site-packages/pydantic/v1/tools.py", line 30, in _get_parsing_type
    return create_model(type_name, __root__=(type_, ...))
  File "/Users/sharathhuddar/workspace/django-rest-api/django-rest-api-3.7/lib/python3.7/site-packages/pydantic/main.py", line 1319, in create_model
    return meta(__model_name, resolved_bases, namespace, __pydantic_reset_parent_namespace__=False, **kwds)
  File "/Users/sharathhuddar/workspace/django-rest-api/django-rest-api-3.7/lib/python3.7/site-packages/pydantic/_internal/_model_construction.py", line 96, in __new__
    namespace, config_wrapper.ignored_types, class_vars, base_field_names
  File "/Users/sharathhuddar/workspace/django-rest-api/django-rest-api-3.7/lib/python3.7/site-packages/pydantic/_internal/_model_construction.py", line 279, in inspect_namespace
    raise TypeError("To define root models, use `pydantic.RootModel` rather than a field called '__root__'")
TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'
```

On inspecting the source code, I noticed that `parse_obj_as` calls `_get_parsing_type` which inturn calls `pydantic.main.create_model` instead of `pydantic.v1.main.create_model`

The issue gets resolved on updating the import statement in `pydantic.v1.tools._get_parsing_type: 24` from `from pydantic.main import create_model` to `from pydantic.v1.main import create_model`

### Python, Pydantic & OS Version

```Text
python -c "import pydantic.version; print(pydantic.version.version_info())"

             pydantic version: 2.0
        pydantic-core version: 2.0.1 release build profile
                 install path: /Users/sharathhuddar/workspace/django-rest-api/django-rest-api-3.7/lib/python3.7/site-packages/pydantic
               python version: 3.7.12 (default, Nov 22 2022, 14:45:00)  [Clang 13.1.6 (clang-1316.0.21.2.5)]
                     platform: Darwin-22.2.0-x86_64-i386-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']
```

Selected Assignee: @lig

**Comment by SharathHuddar** [comment]
Looks like this bug crept in because V1 code that is copied over to `pydantic.v1` has absolute import path. Have raised a [PR](https://github.com/pydantic/pydantic/pull/6364) with relative import path

**Comment by hramezani** [comment]
Fixed in https://github.com/pydantic/pydantic/commit/2c0e2a6d8a961ce320915302caadbb31cc565983

**Comment by Kludex** [comment]
@SharathHuddar We are going to make a release today.

**Comment by jsntcy** [comment]
@Kludex, once the fix is released, please let us know.

**Comment by Kludex** [comment]
Sorry, we didn't make it to release it yesterday, but for sure it will be released today.

You can watch our releases selecting "Watch" -> "Custom" -> "Releases": 
<img width="302" alt="Screenshot 2023-07-04 at 13 47 42" src="https://github.com/pydantic/pydantic/assets/7353520/a9cfcf16-92ae-48b1-96a4-e544889723ff">

**Comment by jsntcy** [comment]
@Kludex @hramezani, the issue still exists using the new version.
We use: pydantic-2.0.1 pydantic-core-2.0.2

**Comment by hramezani** [comment]
@jsntcy Based on the error picture that you posted, Your codebase is using `Pydantic V1`. We had a lot of changes in `Pydantic V2`. So, to fix the problem, you need to

- Update your code base to `Pydantic V2` based on [migration guide](https://docs.pydantic.dev/2.0/migration/)
- Or, Still using `Pydantic V1`. to do this you need to change the imports. e.g. `from pydantic import BaseModel` has to be changed to `from pydantic.v1 import BaseModel`
- Or, if you are not ready to migrate to `V2`, pin pydantic to <2

**Comment by wangzelin007** [comment]
> @jsntcy Based on the error picture that you posted, Your codebase is using `Pydantic V1`. We had a lot of changes in `Pydantic V2`. So, to fix the problem, you need to
> 
> * Update your code base to `Pydantic V2` based on [migration guide](https://docs.pydantic.dev/2.0/migration/)
> * Or, Still using `Pydantic V1`. to do this you need to change the imports. e.g. `from pydantic import BaseModel` has to be changed to `from pydantic.v1 import BaseModel`
> * Or, if you are not ready to migrate to `V2`, pin pydantic to <2

@hramezani,
we ping pydantic to < 2, and actually installed the pydantic 1.10.11, it gives another error `TypeError: unsupported operand type(s) for |: 'ModelMetaclass' and 'NoneType'`, any suggestion?
