### ISSUE TITLE
`validate_assignment=True` and `model_validator "after"` doesn't prevent the improper value from getting through

### ISSUE THREAD

**Issue by ckyoog** [pydantic/pydantic#7105]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

As the example code shows, the model_validator "after" raises an exception if the attribute `d` is set to 100, which works properly. But you will also find the attribute `d` is set to 100 anyway.

The expected result should be the value of `d` remains unchanged, which is 1 in this case.

The builtin validator wouldn't change the value of `d`, when the `d` is assigned a string value as shown in the example code.

### Example Code

```Python
from pydantic import BaseModel, ConfigDict, model_validator
class M(BaseModel):
    d: int
    model_config = ConfigDict(validate_assignment=True)

    @model_validator(mode='after')
    def after(self):
        print('-----', self)
        if self.d == 100:
            raise ValueError("100 is not allowed")
        return self

m = M(d=1)
print(m)

try:
    m.d = 'abc'
except Exception:
    print(m)    # d is 1, not changed

try:
    m.d = 100
except Exception:
    print(m)    # d is set to 100 incorrectly
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=false mimalloc=true
                 install path: /home/ykou/.local/share/virtualenvs/src-Notm8Sad/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, May 18 2023, 16:04:06) [GCC 12.2.0]
                     platform: Linux-6.3.3_1-aarch64-with-glibc2.36
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @davidhewitt

**Comment by davidhewitt** [comment]
I can reproduce this. I have corrected your example so that it runs without any editing needed.

**Comment by davidhewitt** [comment]
The solution is probably quite complicated, because the instance is already updated, we probably need to rollback the assignment.

**Comment by davidhewitt** [comment]
An alternative may be to pass a proxy type to the validator in this case so that we don't need to mutate the instance until after the whole validation has completed.

**Comment by mohaidoss** [comment]
Hi @davidhewitt,
It seems like the bug is still relevant, with `Python 3.10.12` and `pydantic==1.10.13`, what's the status here ? Any plans ?
