### ISSUE TITLE
Pydantic V2 slower on AWS lambda

### ISSUE THREAD

**Issue by matthieudesprez** [pydantic/pydantic#7393]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello,

We've migrated from v1 to v2 in our codebase, and we've experienced slower execution times on AWS lambda, along with memory consumption increase.

<img width="1407" alt="image" src="https://github.com/pydantic/pydantic/assets/13304634/d13ca2cf-0f41-43c0-af99-a53a862e320e">

I'm struggling to reproduce this locally, so for now I thought I could already share it here in case someone has a similar issue.

It doesn't seem to be related to cold start, as even warm lambdas are affected, but it looks like the most "wasted" time happens during the beginning of the execution. It takes 20s to do something I still can't figure.

<img width="1456" alt="image" src="https://github.com/pydantic/pydantic/assets/13304634/20c15675-467c-4e8a-945b-bf42b1009224">

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=false mimalloc=true
                 install path: .../lib/python3.8/site-packages/pydantic
               python version: 3.8.12 (default, Sep  5 2022, 15:57:41)  [Clang 13.1.6 (clang-1316.0.21.2.3)]
                     platform: ...
     optional deps. installed: ['email-validator', 'typing-extensions']
```

**Comment by adriangb** [comment]
Slow cold starts are a known problem.
Memory usage was a problem but should have been solved by https://github.com/pydantic/pydantic-core/pull/900.

I see you're using `pydantic-core` 2.4.0. Can you try updating to the latest `pydantic` (v2.3.0 as or today) and hence the latest `pydantic-core`?

**Comment by matthieudesprez** [comment]
Thanks for your answer. It looks better indeed since upgrading to the last version.

Can we do something in order to optimise the initialisation time ?

**Comment by adriangb** [comment]
Just curious, are you using FastAPI?

**Comment by matthieudesprez** [comment]
Not on this lambda, it's actually triggered by Appsync as a resolver for a GraphQL Query, but it does use 5 levels depth nested models.

Last update seems to work better for now, so I'm gonna close this issue, thanks for your help.

**Comment by matthieudesprez** [comment]
Unfortunately, these idle time of ~20s still occur even with pydantic in 2.3.0 ad pydantic-core in 2.6.3, it was slightly better but still impact our lambda based api.

<img width="1428" alt="image" src="https://github.com/pydantic/pydantic/assets/13304634/1a71d444-9c48-481d-a069-ee8395f1c0e7">

I'm failing to reproduce this locally, and it's happening randomly once deployed, being on 3.8 or 3.10 lambda runtimes.

Well, will have to revert to v1 for now.
